version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "testing-http-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gznh894m47ux"
s3_prefix = "testing-http-api"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
