# Code: https://gist.github.com/JonnyDavies/4c0f23270d04fc0f4ea4e446ed8e496a
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  testing-http-api
  Sample SAM Template for testing-http-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: nonprod

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        GetEmployees:
          Type: HttpApi 
          Properties:
            Path: /employee
            Method: get
            ApiId:
              Ref: HttpApi

        GetEmployee:
          Type: HttpApi 
          Properties:
            Path: /employee/{id}
            Method: get
            ApiId:
              Ref: HttpApi
              
        PostEmployee:
          Type: HttpApi 
          Properties:
            Path: /employee
            Method: post
            ApiId:
              Ref: HttpApi