version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dex1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gznh894m47ux"
s3_prefix = "dex1"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
