version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "polygon"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gznh894m47ux"
s3_prefix = "polygon"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
